"""empty message

Revision ID: 83167d34ee87
Revises: 626ac78ff508
Create Date: 2022-08-08 14:07:29.402160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83167d34ee87'
down_revision = '626ac78ff508'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic', sa.String(length=255), nullable=True))
    op.drop_column('users', 'profile_photo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_photo', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'profile_pic')
    # ### end Alembic commands ###
